### PR TITLE
Fix top five for Topic preview compatibility

### PR DESCRIPTION
**Pull request by VSEphpbb**
Hi Rich. Hopefully you can get this into to Top Five and resubmit it to Titania. It was brought to my attention that this version of Top Five broke its compatibility with Topic Preview.

In this PR I both fixed it to work with Topic Preview and also fixed some HTML tags that were in the wrong position and help guarantee proper layout. I also reflowed the HTML a little bit to make it easier to read.

### CODE REVIEW

**Comment by RMcGirr83** [comment]
Thanks Matt.

**Comment by Galixte** [comment]
Hi @RMcGirr83,

i suppose that since your last commit here: https://github.com/RMcGirr83/phpBB-3.1-topfive/commit/543db4b072529c659d8bf1c029b0a607c4cb82e7 the VSE fix: https://github.com/RMcGirr83/phpBB-3.1-topfive/commit/037b693897fea175f290112e2f0e84d662f56deb was broken and the compatibility with Topic Preview is no longer.

**Comment by RMcGirr83** [comment]
:blush: Yep....fixed.

**Comment by Galixte** [comment]
Hi @RMcGirr83 ,

I’m sorry but the last commits have broken the VSE fix again.

**Comment by VSEphpbb** [comment]
class needs to be topictitle.

**Comment by RMcGirr83** [comment]
GAH!!!

Fixed again

**Comment by Galixte** [comment]
Thanks ;)

**Pull request merged**
